#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PickerItemsFromSQLite.Droid.Resource", IsApplication=true)]

namespace PickerItemsFromSQLite.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Syncfusion.XForms.Android.DataForm.Resource.Drawable.GroupCollapse = global::PickerItemsFromSQLite.Droid.Resource.Drawable.GroupCollapse;
			global::Syncfusion.XForms.Android.DataForm.Resource.Drawable.GroupExpander = global::PickerItemsFromSQLite.Droid.Resource.Drawable.GroupExpander;
			global::Syncfusion.XForms.Android.DataForm.Resource.Layout.Spinner_item = global::PickerItemsFromSQLite.Droid.Resource.Layout.Spinner_item;
			global::Syncfusion.ListView.XForms.Android.Resource.String.ApplicationName = global::PickerItemsFromSQLite.Droid.Resource.String.ApplicationName;
			global::Syncfusion.ListView.XForms.Android.Resource.String.Hello = global::PickerItemsFromSQLite.Droid.Resource.String.Hello;
			global::Syncfusion.ListView.XForms.Android.Resource.String.Load_More = global::PickerItemsFromSQLite.Droid.Resource.String.Load_More;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int GroupCollapse = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int GroupExpander = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Spinner_item = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int SampleSQLites = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Load_More = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
